version: "3.9"

services:
  web:
    build: .
    container_name: pncp-web
    ports:
      - "8000:8000"
    environment:
      - FLASK_ENV=production
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
      - PNCP_API_BASE=https://pncp.gov.br/api/pncp
      - CONSULTA_API_BASE=https://pncp.gov.br/api/consulta
      # Defina SECRET_KEY via variáveis de ambiente ou arquivo .env
      - SECRET_KEY=${SECRET_KEY:-please-set-a-strong-secret}
    depends_on:
      - redis
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://127.0.0.1:8000/api/health"]
      interval: 30s
      timeout: 5s
      retries: 3
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: pncp-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: ["redis-server", "--save", "60", "1", "--loglevel", "warning"]
    restart: unless-stopped

volumes:
  redis_data:
